export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const CREATE_CERTIFICATE='CREATE_CERTIFICATE'
export const DELETE_CERTIFICATE='CREATE_CERTIFICATE'
export const EDIT_CERTIFICATE='CREATE_CERTIFICATE'
export const CREATE_CERTIFICATE='CREATE_CERTIFICATE'
export const CREATE_CERTIFICATE='CREATE_CERTIFICATE'